version: '3.8'

services:
  db:
    image: postgres:14.0-alpine
    ports:
      - "5433"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: python /bookstore/manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/bookstore
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-3wpdkv@ggaib-l&j1u*j2u6q(botxd2-)y@t$$k2^c97@v54+&$$
  
volumes:
  postgres_data: 
